project_id: "prj-xyz-<env>-fruit"
artifact_registry: "australia-southeast1-docker.pkg.dev"
artifact_repo_docker: "rpo-<env>-xyz-fruit-docker"
storage_bucket: "bkt-xyz-<env>-fruit"
service_account: "gsvc-xyz-<env>-fruit"
location: "australia-southeast1"
zone: "australia-southeast1-a"
key_ring_id: "keyring-fruit"
key_id: "key-fruit"
